export const INIT_APP = 'INIT_APP';

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';

export const LOG_IN_FAIL = 'LOG_IN_FAIL';

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const LOG_OUT_FAIL = 'LOG_OUT_FAIL';

export const SEND_CODE_REQUEST = 'SEND_CODE_REQUEST';

export const SEND_CODE_SUCCESS = 'SEND_CODE_SUCCESS';

export const SEND_CODE_FAIL = 'SEND_CODE_FAIL';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_USER_FAIL = 'GET_USER_FAIL';

export const GET_APPLICATION_REQUEST = 'GET_APPLICATION_REQUEST';

export const GET_APPLICATION_SUCCESS = 'GET_APPLICATION_SUCCESS';

export const GET_APPLICATION_FAIL = 'GET_APPLICATION_FAIL';

export const SET_MENU = 'SET_MENU';

export const SET_CHAT = 'SET_CHAT';

export const MENU_OPEN = 'MENU_OPEN';

export const SET_FONT_FAMILY = 'SET_FONT_FAMILY';

export const SET_BORDER_RADIUS = 'SET_BORDER_RADIUS'; 

export const SEND_REPLACEMENT_OFFER_REQUEST = 'SEND_REPLACEMENT_OFFER_REQUEST'; 

export const SEND_REPLACEMENT_OFFER_SUCCESS = 'SEND_REPLACEMENT_OFFER_SUCCESS'; 

export const SEND_REPLACEMENT_OFFER_FAIL = 'SEND_REPLACEMENT_OFFER_FAIL'; 

export const CHOOSE_AUTH_TYPE = 'CHOOSE_AUTH_TYPE'; 

export const CREATE_APPLICATIONS_FROM_EXCEL_REQUEST = 'CREATE_APPLICATIONS_FROM_EXCEL_REQUEST'; 

export const GET_PREAPPROVAL_FORMS_REQUEST = 'GET_PREAPPROVAL_FORMS_REQUEST';

export const GET_PREAPPROVAL_FORMS_SUCCESS = 'GET_PREAPPROVAL_FORMS_SUCCESS'; 

export const GET_PREAPPROVAL_FORMS_FAIL = 'GET_PREAPPROVAL_FORMS_FAIL'; 

export const DELETE_PREAPPROVAL_FORM_REQUEST = 'DELETE_PREAPPROVAL_FORM_REQUEST';

export const DELETE_PREAPPROVAL_FORM_SUCCESS = 'DELETE_PREAPPROVAL_FORM_SUCCESS'; 

export const DELETE_PREAPPROVAL_FORM_FAIL = 'DELETE_PREAPPROVAL_FORM_FAIL'; 

export const GET_COURSE_APPROVAL_REQUESTS_REQUEST = 'GET_COURSE_APPROVALS_REQUEST';

export const GET_COURSE_APPROVAL_REQUESTS_SUCCESS = 'GET_COURSE_APPROVALS_SUCCESS';

export const GET_COURSE_APPROVAL_REQUESTS_FAIL = 'GET_COURSE_APPROVALS_FAIL';

export const DELETE_COURSE_APPROVAL_REQUEST_REQUEST = 'DELETE_COURSE_APPROVAL_REQUEST_REQUEST';

export const DELETE_COURSE_APPROVAL_REQUEST_SUCCESS = 'DELETE_COURSE_APPROVAL_REQUEST_SUCCESS';

export const DELETE_COURSE_APPROVAL_REQUEST_FAIL = 'DELETE_COURSE_APPROVAL_REQUEST_FAIL';

export const ACCEPT_PREAPPROVAL_FORM_REQUEST = 'ACCEPT_PREAPPROVAL_FORM_REQUEST';

export const ACCEPT_PREAPPROVAL_FORM_SUCCESS = 'ACCEPT_PREAPPROVAL_FORM_SUCCESS';

export const ACCEPT_PREAPPROVAL_FORM_FAIL = 'ACCEPT_PREAPPROVAL_FORM_FAIL';

export const DECLINE_PREAPPROVAL_FORM_REQUEST = 'DECLINE_PREAPPROVAL_FORM_REQUEST';

export const DECLINE_PREAPPROVAL_FORM_SUCCESS = 'DECLINE_PREAPPROVAL_FORM_SUCCESS';

export const DECLINE_PREAPPROVAL_FORM_FAIL = 'DECLINE_PREAPPROVAL_FORM_FAIL';

export const ACCEPT_COURSE_APPROVAL_REQUEST_REQUEST = 'ACCEPT_COURSE_APPROVAL_REQUEST_REQUEST';

export const ACCEPT_COURSE_APPROVAL_REQUEST_SUCCESS = 'ACCEPT_COURSE_APPROVAL_REQUEST_SUCCESS';

export const ACCEPT_COURSE_APPROVAL_REQUEST_FAIL = 'ACCEPT_COURSE_APPROVAL_REQUEST_FAIL';

export const DECLINE_COURSE_APPROVAL_REQUEST_REQUEST = 'DECLINE_COURSE_APPROVAL_REQUEST_REQUEST';

export const DECLINE_COURSE_APPROVAL_REQUEST_SUCCESS = 'DECLINE_COURSE_APPROVAL_REQUEST_SUCCESS';

export const DECLINE_COURSE_APPROVAL_REQUEST_FAIL = 'DECLINE_COURSE_APPROVAL_REQUEST_FAIL';

export const CREATE_COURSE_APPROVAL_REQUEST_REQUEST = 'CREATE_COURSE_APPROVAL_REQUEST_REQUEST';

export const CREATE_COURSE_APPROVAL_REQUEST_SUCCESS = 'CREATE_COURSE_APPROVAL_REQUEST_SUCCESS'; 

export const CREATE_COURSE_APPROVAL_REQUEST_FAIL = 'CREATE_COURSE_APPROVAL_REQUEST_FAIL'; 

export const CREATE_PREAPPROVAL_FORM_REQUEST = 'CREATE_PREAPPROVAL_FORM_REQUEST';

export const CREATE_PREAPPROVAL_FORM_SUCCES = 'CREATE_PREAPPROVAL_FORM_SUCCES';

export const CREATE_PREAPPROVAL_FORM_FAIL = 'CREATE_PREAPPROVAL_FORM_FAIL';

export const GET_COURSES_BY_DEPARTMENT_REQUEST = 'GET_COURSES_BY_DEPARTMENT_REQUEST';

export const GET_COURSES_BY_DEPARTMENT_SUCCESS = 'GET_COURSES_BY_DEPARTMENT_SUCCESS';

export const GET_COURSES_BY_DEPARTMENT_FAIL = 'GET_COURSES_BY_DEPARTMENT_FAIL';

export const GET_APPLICATIONS_BY_DEPARTMENT_REQUEST = 'GET_APPLICATIONS_BY_DEPARTMENT_REQUEST';

export const GET_APPLICATIONS_BY_DEPARTMENT_SUCCESS = 'GET_APPLICATIONS_BY_DEPARTMENT_SUCCESS';

export const GET_APPLICATIONS_BY_DEPARTMENT_FAIL = 'GET_APPLICATIONS_BY_DEPARTMENT_FAIL';

export const GET_ANNOUNCEMENTS_REQUEST = 'GET_ANNOUNCEMENTS_REQUEST';

export const GET_ANNOUNCEMENTS_SUCCESS = 'GET_ANNOUNCEMENTS_SUCCESS';

export const GET_ANNOUNCEMENTS_FAIL = 'GET_ANNOUNCEMENTS_FAIL';

export const CREATE_ANNOUNCEMENT_REQUEST = 'CREATE_ANNOUNCEMENT_REQUEST';

export const CREATE_ANNOUNCEMENT_SUCCESS = 'CREATE_ANNOUNCEMENT_SUCCESS';

export const CREATE_ANNOUNCEMENT_FAIL = 'CREATE_ANNOUNCEMENT_FAIL';

export const DELETE_ANNOUNCEMENT_REQUEST = 'DELETE_ANNOUNCEMENT_REQUEST';

export const DELETE_ANNOUNCEMENT_SUCCESS = 'DELETE_ANNOUNCEMENT_SUCCESS';

export const DELETE_ANNOUNCEMENT_FAIL = 'DELETE_ANNOUNCEMENT_FAIL';

export const GET_DEPARTMENTS_REQUEST = 'GET_DEPARTMENTS_REQUEST';

export const GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS';

export const GET_DEPARTMENTS_FAIL = 'GET_DEPARTMENTS_FAIL';

export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';

export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';

export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';

export const DELETE_UNIVERSITY_REQUEST = 'DELETE_UNIVERSITY_REQUEST';

export const DELETE_UNIVERSITY_SUCCESS = 'DELETE_UNIVERSITY_SUCCESS';

export const DELETE_UNIVERSITY_FAIL = 'DELETE_UNIVERSITY_FAIL';

export const MARK_NOTIFICATION_READ_REQUEST = 'MARK_NOTIFICATION_READ_REQUEST';

export const MARK_NOTIFICATION_READ_SUCCESS = 'MARK_NOTIFICATION_READ_SUCCESS';

export const MARK_NOTIFICATION_READ_FAIL = 'MARK_NOTIFICATION_READ_FAIL';

export const GET_FILE_REQUESTS_REQUEST = 'GET_FILE_REQUESTS_REQUEST';

export const GET_FILE_REQUESTS_SUCCESS = 'GET_FILE_REQUESTS_SUCCESS';

export const GET_FILE_REQUESTS_FAIL = 'GET_FILE_REQUESTS_FAIL';

export const DELETE_FILE_REQUEST_REQUEST = 'DELETE_FILE_REQUEST_REQUEST';

export const DELETE_FILE_REQUEST_SUCCESS = 'DELETE_FILE_REQUEST_SUCCESS';

export const DELETE_FILE_REQUEST_FAIL = 'DELETE_FILE_REQUEST_FAIL';

export const CREATE_FILE_REQUEST_REQUEST = 'CREATE_FILE_REQUEST_REQUEST';

export const CREATE_FILE_REQUEST_SUCCESS = 'CREATE_FILE_REQUEST_SUCCESS';

export const CREATE_FILE_REQUEST_FAIL = 'CREATE_FILE_REQUEST_FAIL';

export const RESPOND_FILE_REQUEST_REQUEST = 'RESPOND_FILE_REQUEST_REQUEST';

export const RESPOND_FILE_REQUEST_SUCCESS = 'RESPOND_FILE_REQUEST_SUCCESS';

export const RESPOND_FILE_REQUEST_FAIL = 'RESPOND_FILE_REQUEST_FAIL';

export const GET_UNIVERSITIES_REQUEST = 'GET_UNIVERSITIES_REQUEST';

export const GET_UNIVERSITIES_SUCCESS = 'GET_UNIVERSITIES_SUCCESS';

export const GET_UNIVERSITIES_FAIL = 'GET_UNIVERSITIES_FAIL';

export const ADD_UNIVERSITY_REQUEST = 'ADD_UNIVERSITY_REQUEST';

export const ADD_UNIVERSITY_SUCCESS = 'ADD_UNIVERSITY_SUCCESS';

export const ADD_UNIVERSITY_FAIL = 'ADD_UNIVERSITY_FAIL';















