export const INIT_APP = 'INIT_APP';

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';

export const LOG_IN_FAIL = 'LOG_IN_FAIL';

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const LOG_OUT_FAIL = 'LOG_OUT_FAIL';

export const SEND_CODE_REQUEST = 'SEND_CODE_REQUEST';

export const SEND_CODE_SUCCESS = 'SEND_CODE_SUCCESS';

export const SEND_CODE_FAIL = 'SEND_CODE_FAIL';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_USER = 'GET_USER';

export const SET_MENU = 'SET_MENU';

export const SET_CHAT = 'SET_CHAT';

export const MENU_OPEN = 'MENU_OPEN';

export const SET_FONT_FAMILY = 'SET_FONT_FAMILY';

export const SET_BORDER_RADIUS = 'SET_BORDER_RADIUS'; 

export const SEND_REPLACEMENT_OFFER_REQUEST = 'SEND_REPLACEMENT_OFFER_REQUEST'; 

export const SEND_REPLACEMENT_OFFER_SUCCESS = 'SEND_REPLACEMENT_OFFER_SUCCESS'; 

export const SEND_REPLACEMENT_OFFER_FAIL = 'SEND_REPLACEMENT_OFFER_FAIL'; 

export const CHOOSE_AUTH_TYPE = 'CHOOSE_AUTH_TYPE'; 

export const CREATE_APPLICATIONS_FROM_EXCEL_REQUEST = 'CREATE_APPLICATIONS_FROM_EXCEL_REQUEST'; 

export const GET_PREAPPROVAL_FORMS_REQUEST = 'GET_PREAPPROVAL_FORMS_REQUEST';

export const GET_PREAPPROVAL_FORMS_SUCCESS = 'GET_PREAPPROVAL_FORMS_SUCCESS'; 

export const GET_PREAPPROVAL_FORMS_FAIL = 'GET_PREAPPROVAL_FORMS_FAIL'; 

export const DELETE_PREAPPROVAL_FORM_REQUEST = 'DELETE_PREAPPROVAL_FORM_REQUEST';

export const DELETE_PREAPPROVAL_FORM_SUCCESS = 'DELETE_PREAPPROVAL_FORM_SUCCESS'; 

export const DELETE_PREAPPROVAL_FORM_FAIL = 'DELETE_PREAPPROVAL_FORM_FAIL'; 

export const GET_COURSE_APPROVAL_REQUESTS_REQUEST = 'GET_COURSE_APPROVALS_REQUEST';

export const GET_COURSE_APPROVAL_REQUESTS_SUCCESS = 'GET_COURSE_APPROVALS_SUCCESS';

export const GET_COURSE_APPROVAL_REQUESTS_FAIL = 'GET_COURSE_APPROVALS_FAIL';










