export const INIT_APP = 'INIT_APP';

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';

export const LOG_IN_FAIL = 'LOG_IN_FAIL';

export const LOG_OUT = 'LOG_OUT';

export const SEND_CODE_REQUEST = 'SEND_CODE_REQUEST';

export const SEND_CODE_SUCCESS = 'SEND_CODE_SUCCESS';

export const SEND_CODE_FAIL = 'SEND_CODE_FAIL';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
