const INITIAL_STATE = {
    allUsers: [
      {
          id: 1,
          name: "John Doe",
          actorType: "Outgoing Student",
          type: 'Erasmus',
          department: "Computer Science",
          selectedUniversities: [],
          selectedSemester: 'fall',
          score: 67,
          status: "waiting",
          admittedUniversity: null,
          documents: [],
      },{
          id: 2,
          name: "Kürşad Güzelkaya",
          actorType: "Outgoing Student",
          type: 'Erasmus',
          department: "Computer Science",
          selectedUniversities: [],
          selectedSemester: 'fall',
          score: 77,
          status: "waiting",
          admittedUniversity: null,
          documents: [],
      },{
          id: 3,
          name: "Jake Paul",
          actorType: "Outgoing Student",
          type: 'Erasmus',
          department: "Computer Science",
          selectedUniversities: [],
          selectedSemester: 'fall',
          score: 80,
          status: "waiting",
          admittedUniversity: null,
          documents: [],
      },{
          id: 4,
          name: "Lionel Messi",
          actorType: "Incoming Student",
          type: 'Erasmus',
          department: "Computer Science",
          selectedUniversities: [],
          selectedSemester: 'fall',
          score: 69,
          status: "waiting",
          admittedUniversity: null,
          documents: [],
      },{
          id: 5,
          name: "Cristiano Ronaldo",
          actorType: "Incoming Student",
          type: 'Erasmus',
          department: "Mechanical Engineering",
          selectedUniversities: [],
          selectedSemester: 'fall',
          score: 85,
          status: "waiting",
          admittedUniversity: null,
          documents: [],
      },
        {
          id: 6,
          name: "Bekir Emir Şanlı",
          actorType: "Outgoing Student",
          type: 'Erasmus',
          department: "Computer Science",
          selectedUniversities: ["Bilkent University", "Stanford University", "Harvard University", "Ohio State University", "MIT"],
          selectedSemester: 'fall',
          score: 67,
          status: "placed",
          admittedUniversity: "Stanford",
          documents: [],
      },{
          id: 7,
          name: "Gökhan Tekin",
          actorType: "Outgoing Student",
          type: 'Erasmus',
          department: "Computer Science",
          selectedUniversities: ["Bilkent University", "Stanford University", "Harvard University", "Ohio State University", "MIT"],
          selectedSemester: 'spring',
          score: 77,
          status: "placed",
          admittedUniversity: "Harward",
          documents: [],
      },{
          id: 8,
          name: "Hazal Buluş",
          actorType: "Outgoing Student",
          type: 'Erasmus',
          department: "Electrical Engineering",
          selectedUniversities: ["Bilkent University", "Stanford University", "Harvard University", "Ohio State University", "MIT"],
          selectedSemester: 'fall',
          score: 80,
          status: "placed",
          admittedUniversity: "MIT",
          documents: [],
      },{
          id: 9,
          name: "Chris Jenner",
          actorType: "Outgoing Student",
          type: 'Erasmus',
          department: "Computer Science",
          selectedUniversities: ["Bilkent University", "Stanford University", "Harvard University", "Ohio State University", "MIT"],
          selectedSemester: 'spring',
          score: 69,
          status: "placed",
          admittedUniversity: "UCLA",
          documents: [],
      },{
          id: 10,
          name: "Can Alkan",
          actorType: "Department Coordinator",
          department: "Computer Science",
          documents: [],
      },
      {
        id: 11,
        name: "Yelda Ateş",
        actorType: "Administrative Staff",
        documents: [],
    },
    {
        id: 12,
        name: "Eray Tüzün",
        actorType: "Course Coordinator",
        department: "Computer Science",
        courses: [],
        documents: [],
    },
    ],
  };
  
  const adminUserReducer = (state = INITIAL_STATE, action) => {
    switch (action.type) {
      default:
        return state;
    }
  };
  
  export default adminUserReducer;
  